spring:
  application:
    name: english-learning-app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:english_learning_app;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
